### PR TITLE
Added selectionControls property

### LINKED ISSUE #68: Enable Selection for disabled Textfield
Hi, 

I am using the CodeField mainly for displaying code, rather then writing it. So mainly I have it "enabled = false". Nonetheless I'd like to select some code snippets here and there, but as I see, the selection is only possible on enabled/writeable Textfields.

Is this possible?

Thanks in advance,
Mark

### PR DESCRIPTION
**Pull request by gumbarros**
Added this [property](https://api.flutter.dev/flutter/widgets/EditableText/selectionControls.html) from TextField.
This closes #68

### CODE REVIEW

**Comment by S-Man42** [comment]
Thank you so much!

**Comment by gumbarros** [comment]
Good morning @BertrandBev! Will this be merged 🙂 ?

**Comment by BertrandBev** [comment]
> Good morning @BertrandBev! Will this be merged 🙂 ?

Sure thing! Thanks!

**Comment by S-Man42** [comment]
Is this released to the pub.dev? The last changelog does not mention it.

**Pull request merged**
